version: '3'

services:

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=3115
      - DB_NAME=shop_db
    depends_on:
      - postgres

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=shop_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3115
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: